In [7]:
#import matplotlib.pyplot as plt
#import seaborn as sns
import pandas as pd
from bokeh.charts import BoxPlot, Scatter, show

auto = pd.read_csv("Automobile_price_data _clean.csv")
autoND = pd.read_csv("Automobile_price_data _NoDash.csv")

In [2]:
auto.head()

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,honda,gas,std,two,hatchback,fwd,front,86.6,144.6,63.9,...,92,1bbl,2.91,3.41,9.6,58,4800,49,54,6479
1,chevrolet,gas,std,two,hatchback,fwd,front,88.4,141.1,60.3,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
2,nissan,diesel,std,two,sedan,fwd,front,94.5,165.3,63.8,...,103,idi,2.99,3.47,21.9,55,4800,45,50,7099
3,toyota,diesel,std,four,hatchback,fwd,front,95.7,166.3,64.4,...,110,idi,3.27,3.35,22.5,56,4500,38,47,7788
4,toyota,gas,std,four,sedan,fwd,front,95.7,166.3,64.4,...,98,2bbl,3.19,3.03,9.0,70,4800,38,47,7738

In [3]:
autoND.head()

,make,fueltype,aspiration,numofdoors,bodystyle,drivewheels,enginelocation,wheelbase,length,width,...,enginesize,fuelsystem,bore,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,honda,gas,std,two,hatchback,fwd,front,86.6,144.6,63.9,...,92,1bbl,2.91,3.41,9.6,58,4800,49,54,6479
1,chevrolet,gas,std,two,hatchback,fwd,front,88.4,141.1,60.3,...,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
2,nissan,diesel,std,two,sedan,fwd,front,94.5,165.3,63.8,...,103,idi,2.99,3.47,21.9,55,4800,45,50,7099
3,toyota,diesel,std,four,hatchback,fwd,front,95.7,166.3,64.4,...,110,idi,3.27,3.35,22.5,56,4500,38,47,7788
4,toyota,gas,std,four,sedan,fwd,front,95.7,166.3,64.4,...,98,2bbl,3.19,3.03,9.0,70,4800,38,47,7738

In [11]:
p = BoxPlot(auto, values = "price", label = ["make", "body-style"], color = "make", plot_width = 1000, plot_height = 800, title = "Price Summary (grouped by make,body-style)")
show(p)

In [5]:
tooltips=[
  ('Price', '@price'),
  ('Make', '@make'),
  ('Body-style', '@bodystyle'),
  ('City-mpg', '@citympg'),    
]

p2 = Scatter(autoND, x = "citympg", y = "price", color = "make", marker = "bodystyle", title = "LAS350A - Lab 10: Price vs City-mpg (shaded by Make, maker by Body-style)", plot_width = 1000, plot_height = 800, tooltips=tooltips)
show(p2)

In [10]:
test = auto[['make', 'body-style']]
test.head()

        make body-style
0      honda  hatchback
1  chevrolet  hatchback
2     nissan      sedan
3     toyota  hatchback
4     toyota      sedan

The most efficient city-mpg sedan is a Nissan. It has a city mpg of 45 and a price of 7099.